const quoteList = [
    { content: "Stay hungry, stay foolish.", translation: "求知若饥，虚心若愚。", author: "Steve Jobs (English)" },
    { content: "La vie est une fleur dont l'amour est le miel.", translation: "生活是花，爱是蜜。", author: "Victor Hugo (French)" },
    { content: "Wer den Tag mit einem Lachen beginnt, hat ihn bereits gewonnen.", translation: "以微笑开始一天的人，已经赢得了这一天。", author: "Cicero (German)" },
    { content: "七転び八起き (Nana korobi ya oki)", translation: "七跌八起（百折不挠）。", author: "Japanese Proverb" },
    { content: "Carpe diem.", translation: "活在当下（抓紧时间）。", author: "Horace (Latin)" },
    { content: "El que busca, encuentra.", translation: "有志者，事竟成（寻找者必寻见）。", author: "Spanish Proverb" },
    { content: "Hope is a waking dream.", translation: "希望是清醒时的梦想。", author: "Aristotle (English)" },
    { content: "Il sole bacia i belli.", translation: "阳光亲吻美丽的人（天道酬勤）。", author: "Italian Proverb" },
    { content: "雨降って地固まる (Ame futte ji katamaru)", translation: "雨后地更坚（不打不相识/坏事变好事）。", author: "Japanese Proverb" },
    { content: "Vouloir, c’est pouvoir.", translation: "有志者事竟成。", author: "French Proverb" },
    { content: "Per aspera ad astra.", translation: "循此苦旅，以达天际。", author: "Latin Phrase" },
    { content: "Alles hat ein Ende, nur die Wurst hat zwei.", translation: "万物皆有终，唯香肠有两头（以此幽默看待结束）。", author: "German Proverb" },
    { content: "Tomorrow is another day.", translation: "明天又是新的一天。", author: "Gone with the Wind (English)" },
    { content: "C'est la vie.", translation: "这就是生活。", author: "French Phrase" },
    { content: "¡Viva la vida!", translation: "生命万岁！", author: "Frida Kahlo (Spanish)" },
    { content: "初心忘るべからず (Shoshin wasuru bekarazu)", translation: "勿忘初心。", author: "Zeami (Japanese)" },
    { content: "Fortune favors the bold.", translation: "幸运眷顾勇者。", author: "Virgil (English)" },
    { content: "L'essentiel est invisible pour les yeux.", translation: "本质是肉眼看不见的。", author: "Le Petit Prince (French)" },
    { content: "Übung macht den Meister.", translation: "熟能生巧。", author: "German Proverb" },
    { content: "No hay mal que por bien no venga.", translation: "塞翁失马，焉知非福。", author: "Spanish Proverb" },
    { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", translation: "面向阳光，阴影就在你身后。", author: "Walt Whitman (English)" },
    { content: "Amor vincit omnia.", translation: "爱能战胜一切。", author: "Virgil (Latin)" },
    { content: "継続は力なり (Keizoku wa chikara nari)", translation: "坚持就是力量。", author: "Japanese Proverb" },
    { content: "Je pense, donc je suis.", translation: "我思故我在。", author: "Descartes (French)" },
    { content: "What doesn't kill you makes you stronger.", translation: "杀不死你的，会让你更强大。", author: "Nietzsche (English)" },
    { content: "Dum spiro spero.", translation: "只要一息尚存，就拥有希望。", author: "Latin Phrase" },
    { content: "Chi la dura la vince.", translation: "坚持到底者胜。", author: "Italian Proverb" },
    { content: "千里の道も一歩から (Senri no michi mo ippo kara)", translation: "千里之行，始于足下。", author: "Japanese Proverb" },
    { content: "Life is short, make it sweet.", translation: "人生苦短，让它甜美。", author: "English Saying" },
    { content: "La beauté sauvera le monde.", translation: "美将拯救世界。", author: "Dostoevsky (French)" },
    // 你可以在这里按照格式继续添加，直到 365 句...
];
